version: "3.3"

services:
  fetcher:
    container_name: "fetcher"
    build:
      context: ./build
    working_dir: /app
    #command: tail -f /dev/null
    #command: ../init.sh
    environment:
      - GIT_REPOSITORY=${GIT_REPOSITORY:-git@github.com:kubero-dev/template-nodeapp.git}
      - GIT_BRANCH=${GIT_BRANCH:-main}
    volumes:
      - ../../data:/app
      - ../../keys/deploykey:/root/.ssh/deploykey
      - ../../keys/deploykey:/home/kubero/.ssh-mounted/deploykey